POST {{baseUrl}}/places
content-type: application/json

{
    "title" : "New place a its ref",
    "description" : "This is the new description",
    "address" : "Lakhimpur",
    "coordinates" : {
        "lat" : 40.234,
        "long" : 32.0897
    },
    "creator" : "66225f8d909b3c7c041db46c"
}

###
PATCH {{baseUrl}}/places
content-type: application/json

{
    "placeId" : "6620af098bdfb9177fc58e85",
    "title" : "This is new place",
    "description" : "This is the new description"
}

###
GET {{baseUrl}}/places/66225f8d909b3c7c041db46c
content-type : application/json
###

### 
GET {{baseUrl}}/places/user/66225f8d909b3c7c041db46c
content-type : application/json

###

DELETE {{baseUrl}}/places/66225fba909b3c7c041db471
content-type : 'application/json'



