POST {{baseUrl}}/places
content-type: application/json

{
    "title" : "odsfdsg",
    "description" : "This is the new description",
    "address" : "Lakhimpur",
    "coordinates" : {
        "lat" : 40.234,
        "long" : 32.0897
    },
    "creator" : "Nayan"
}

###
PATCH {{baseUrl}}/places
content-type: application/json

{
    "placeId" : "p1",
    "title" : "This is new place",
    "description" : "This is the new description"
}

###

DELETE {{baseUrl}}/places/p1
content-type : 'application/json'



