GET {{baseUrl}}/users

###
POST {{baseUrl}}/users/signup
content-type : application/json

{
    "name" : "Nayan",
    "email" : "nayan2@gmail.com",
    "password" : "nayan@4"
}

###

POST {{baseUrl}}/users/login
content-type : application/json

{
    "email" : "nayan1@gmail.com",
    "password" : "nayan@4"
}

###
POST {{baseUrl}}/users/oauth/google
content-type : application/json

###
###redirect URL

GET {{baseUrl}}/oauth/users/callback/google